version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynet:

volumes:
  postgres_data:
