version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=appdb;Username=postgres;Password=yourpassword
    depends_on:
      - db
    command: >
      sh -c "dotnet ef database update && dotnet webapp_MVC.dll"

  db:
    image: postgres:15
    restart: always 
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
